Silence conda warning in GitHub Actions (#36)
### Testing
```
(bokeh) jessicas-mbp:bokeh jessicacovington$ a bokeh ; env | grep -E '(VIRTUAL|CONDA)'; python -c 'import certifi; print(certifi.__path__)'
/Users/jessicacovington/miniconda3/envs/bokeh/bin/python 3.12.0
ERROR: /Users/jessicacovington/miniconda3/envs/bokeh/bin/python version 3.12.0 does not match .python-version 3.11.7
CONDA_SHLVL=1
CONDA_PROMPT_MODIFIER=(bokeh)
GSETTINGS_SCHEMA_DIR_CONDA_BACKUP=
CONDA_EXE=/Users/jessicacovington/miniconda3/bin/conda
_CE_CONDA=
CONDA_PREFIX=/Users/jessicacovington/miniconda3/envs/bokeh
CONDA_PYTHON_EXE=/Users/jessicacovington/miniconda3/bin/python
CONDA_DEFAULT_ENV=bokeh
['/Users/jessicacovington/miniconda3/envs/bokeh/lib/python3.12/site-packages/certifi']
(bokeh) jessicas-mbp:bokeh jessicacovington$ a helicopyter ; env | grep -E '(VIRTUAL|CONDA)'; python -c 'import certifi; print(certifi.__path__)'
/Users/jessicacovington/prj/helicopyter/.venv/bin/python 3.12.3
/Users/jessicacovington/.asdf/shims/node v20.17.0
CONDA_SHLVL=0
CONDA_EXE=/Users/jessicacovington/miniconda3/bin/conda
VIRTUAL_ENV=/Users/jessicacovington/prj/helicopyter/.venv
_CE_CONDA=
CONDA_PYTHON_EXE=/Users/jessicacovington/miniconda3/bin/python
VIRTUAL_ENV_PROMPT=(.venv)
['/Users/jessicacovington/prj/helicopyter/.venv/lib/python3.12/site-packages/certifi']
(.venv) jessicas-mbp:helicopyter jessicacovington$ a
/Users/jessicacovington/prj/helicopyter/.venv/bin/python 3.12.3
/Users/jessicacovington/.asdf/shims/node v20.17.0
(.venv) jessicas-mbp:helicopyter jessicacovington$ a allowedflare ;  env | grep -E '(VIRTUAL|CONDA)'; python -c 'import certifi; print(certifi.__path__)'
/Users/jessicacovington/prj/allowedflare/.venv/bin/python 3.12.3
/Users/jessicacovington/.asdf/shims/node v20.11.1
CONDA_SHLVL=0
CONDA_EXE=/Users/jessicacovington/miniconda3/bin/conda
VIRTUAL_ENV=/Users/jessicacovington/prj/allowedflare/.venv
_CE_CONDA=
CONDA_PYTHON_EXE=/Users/jessicacovington/miniconda3/bin/python
VIRTUAL_ENV_PROMPT=(.venv)
['/Users/jessicacovington/prj/allowedflare/.venv/lib/python3.12/site-packages/certifi']
```

## Followup
* Figure out how to use asdf-vm in GitHub Actions, so the local
development approach is continuously tested by GitHub Actions